version: "3.9"

services:
  logs-service:
    container_name: logs-service
    build: .
    image: logs-test
    command: /user/local/entrypoint.sh
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB_NAME=log_db
      - DB_PORT=5432
      - DB_HOST=db
      - DB_USER=fable101
      - DB_PASSWORD=fable101
      - DEBUG_MODE=True
    ports:
      - "5050:5050"
    volumes:
      - ./src/:/src/

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=log_db
      - POSTGRES_USER=fable101
      - POSTGRES_PASSWORD=fable101
    expose:
      - 5432
    volumes:
      - ./postgres_db:/var/lib/mysql

